version: '3.1'
services:
  web-app:
    image: vpjaseem/httpd-custom-website
    container_name: web-app
    domainname: web-app.com
    hostname: web-app
    volumes:
      - /root/Desktop/web-app-wwwroot:/usr/local/apache2/htdocs
    ports:
      - '80:80'